### ISSUE TITLE
Missing Native Module files in Published package

### ISSUE THREAD

**Issue by Ananthakr** [loadsmart/rn-salesforce-chat#16]
Since package.json has 
```
 "files": [
    "lib"
  ],
```
it only takes the files from `lib` folder for the package published on the npm. So when someone tries to install via npm/yarn, the native modules are missing in the `node_modules` and if they call the exposed apis, they fail due to lack native modules. 

Please address this issue asap.

**Comment by lenoirzamboni** [comment]
@Ananthakr Thanks for reporting this issue. A new version 2.0.1 is released with the fix.

Closing issue.
