### ISSUE TITLE
Connect to specific agent

### ISSUE THREAD

**Issue by ignaciosanhkhipu** [loadsmart/rn-salesforce-chat#19]
Hello, 
Is there a way to add in the configureChat, when we pass the chatConfig interface, to connect to a specific agent? or how can I do it?.

**Comment by lenoirzamboni** [comment]
Hello @ignaciosanhkhipu!

It seems that the Salesforce API does not support this feature yet, so we are not able to do so. Would mind explaining why are you trying to configure a chat with a specific agent?

Thanks!

**Comment by ignaciosanhkhipu** [comment]
Hello @lenoirzamboni , thanks for the answer. Currently, the application connects to the first available agent, but I need to redirect to a specific agent. The solution is for a bank, so the agent is actually the person's bank account executive, that's why it needs to be a targetted agent, and in the web version, there is a parameter to specify the agent id.

**Comment by lenoirzamboni** [comment]
@ignaciosanhkhipu Hello again! Did you manage to find a solution to your problem?

**Comment by ignaciosanhkhipu** [comment]
Yes, we implemented a webview of a webpage that uses the web plugin. 
Thanks for the concern :)

**Comment by lenoirzamboni** [comment]
Cool! That's nice! 

I will close this issue then, and keep an eye if someday Salesforce API can support connection to a specific agent.
