### ISSUE TITLE
How to hide modal chat?

### ISSUE THREAD

**Issue by sendipatryjar** [loadsmart/rn-salesforce-chat#33]
**Describe the issue**
I want to force the user to logout and close the chat modal, how can I close the modal? is there a function that handles that?

**Smartphone (please complete the following information):**
 - Device: [Iphone 11]
 - OS: [Ios 14.4]

**rn-salesforce-chat version (please complete the following information):**
 - Version: [3.3.0]

**Screenshots**
<img width="312" alt="gambar" src="https://user-images.githubusercontent.com/26238022/170927973-0b52a96b-3ec3-4d1d-a68a-eca0025d7c22.png">

**Comment by lenoirzamboni** [comment]
Hello @sendipatryjar. Right now, the Salesforce SDK does not offer this possibility. if someday this is available, we will definitely implement it.

**Comment by Shahzad101digital** [comment]
Add this method in **RNSalesforceChatModule.java**


`@ReactMethod
	public void endSession(final Callback failureCallback, final Callback successCallback) {
		Runnable endChatRunnable = new Runnable() {
			@Override
			public void run() {
				if (_chatUIClient == null) {
					failureCallback.invoke("error - chat not active");
					return;
				}
				_chatUIClient.endChatSession();
				successCallback.invoke();
			}
		};

		reactContext.runOnUiQueueThread(endChatRunnable);
	}`
